import Sidebar from '@/components/sidebar/Sidebar';
import { Roboto } from 'next/font/google';
import getCurrentUser from '../actions/getCurrentUser';
import { redirect } from 'next/navigation';
import Heading from '@/components/heading/Heading';
import ToasterProvider from '../Providers/ToasterProvider';
import blob from '../../../public/blob.svg';
import Image from 'next/image';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const user = await getCurrentUser();
	if (!user) {
		redirect('/');
	} else
		return (
			<html lang='en'>
				<body className={`${roboto.className} w-screen overflow-x-hidden`}>
					<ToasterProvider />
					<div className='flex relative'>
						<Sidebar />
						<div className='min-h-screen text-neutral-800 p-8 pl-[300px]'>
							<Heading title='Dashboard' checkPath />
							<br />
							{children}
						</div>
						<Image
							src={blob}
							width={350}
							height={350}
							alt='blob'
							className='absolute bottom-[-50px] right-[-50px] opacity-10 -z-10'
						/>
					</div>
				</body>
			</html>
		);
}
