import Sidebar from '@/components/sidebar/Sidebar';
import { Roboto } from 'next/font/google';
import getCurrentUser from '../actions/getCurrentUser';
import { redirect } from 'next/navigation';
import Heading from '@/components/heading/Heading';
import ToasterProvider from '../Providers/ToasterProvider';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const user = await getCurrentUser();
	if (!user) {
		redirect('/');
	} else
		return (
			<html lang='en'>
				<body className={roboto.className}>
					<ToasterProvider />
					<div className='flex relative'>
						<Sidebar />
						<div className='w-full min-h-screen text-neutral-800 p-8 pl-[300px]'>
							<Heading title='Dashboard' checkPath />
							<br />
							{children}
						</div>
					</div>
				</body>
			</html>
		);
}
